# Generated by Django 4.1 on 2024-01-31 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bit',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
