# Generated by Django 4.1 on 2024-01-31 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0002_user_bit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='bit',
            new_name='bio',
        ),
    ]
